#!/bin/bash

# Create a log folder if it doesn't already exist
mkdir -p ../log

# Get current timestamp in the format of yyyy-mm-dd_HH-MM-SS
timestamp=$(date +%Y-%m-%d_%H-%M-%S)

# Build log file name with timestamp
log_file=log/exam_${timestamp}.txt

# Run tcpdump with the specified filter and save the output to the log file
sudo tcpdump -nn -S -i any tcp port 8080 -l | tee $log_file